import localFont from "next/font/local";
import StyledComponentsRegistry from "./registry";
import "./globals.css";
import { GlobalStyles } from "./styles/GlobalStyle";
import { Raleway, Preahvihear } from 'next/font/google'


export const metadata = {
  title: "Idowu Micheal Portfolio",
  description: "Generated by create next app",
};

export const raleway = Raleway({ 
  subsets: ['latin'],
  variable: '--font-raleway', // Add this line
})

export const preahvihear = Preahvihear({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-preahvihear', // Add this line
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${raleway.variable} ${preahvihear.variable}`}>
      <body className={`${raleway.className} ${preahvihear.className}`}>
        <StyledComponentsRegistry>
          {children}
        <GlobalStyles />
        </StyledComponentsRegistry>
      </body>
      
    </html>
  );
}
